Criando a versão 0.1 do modulo de compute do GCP .
Co-authored-by:
adrian.w.roque@gmail.com
Anderson Pereira
Evandro Francisco
Felipe Nobrega
G Batista
Lm Oliveira
Luiz Aoqui
Marcio Machado
Marcelo Mansus
Plinio
tanquetav
mentoriaiac/iac-modulo-compute-gcp pull request #1
Opened 2021-07-03 19:47 UTC by Rehzende

2021-07-09 12:47 UTC, edsoncelio reviewed
Deixei alguns comentários, mas no geral está muito bom, parabéns @Rehzende!

2021-07-09 12:47 UTC, edsoncelio commented on Makefile
> +dummy:
Acho que esses passos 'dummy' poderiam ser removidos, o que acha @Rehzende?

2021-07-09 12:47 UTC, edsoncelio commented on how-to-use-this-module/terrafile.tf
> +}
Aqui é só a linha no final do arquivo :p

2021-07-09 12:47 UTC, edsoncelio commented on main.tf
> +}
Linha no final do arquivo :p

2021-07-10 03:31 UTC, Rehzende commented on Makefile
> +dummy:
removido, não há necessidade dela.

2021-07-10 03:31 UTC, Rehzende commented on how-to-use-this-module/terrafile.tf
> +}
Ajustado.

2021-07-10 03:32 UTC, Rehzende commented on main.tf
> +}
Ajustado

2021-07-10 21:12 UTC, gomex requested changes
Atualiza o README colocando os detalhes de autenticação do Google Cloud usando conta de serviço ;)

2021-07-12 12:55 UTC, gomex commented on versions.tf
> +}
Coloca uma linha em branco aqui tb?

2021-07-12 13:10 UTC, Rehzende commented on versions.tf
> +}
resolvido

2021-07-12 13:10 UTC, Rehzende commented on .github/workflows/ci.yml
> +          terraform_version: 0.14.0
Atualizado

2021-07-12 13:14 UTC, gomex approved these changes
LGTM

2021-07-12 13:14 UTC, merged