feat(acesso): Cria usuário e adiciona chave ssh
mentoriaiac/iac-modulo-compute-gcp pull request #7
Opened 2021-09-26 22:43 UTC by snifbr

# Cria usuário e adiciona chave ssh

Adiciona parâmetro `metadata = { ssh-keys }` no resource
`google_compute_instance` para que seja possível a criação de um usuário
e conta com acesso SSH vinculado a uma chave pública. Houve mudanças no
`.env.terraform` para acomadar variáveis para o uso do Makefile, assim
como foram inseridas 4 novas funções no Makefile para criar conta de
serviço no GCP.

Signed-off-by: Danilo Figueiredo Rocha <snifbr@gmail.com>
Co-authored-by: Gabriel Iglesias <nerdtux@users.noreply.github.com>
Co-authored-by: Felipe Nobrega <lipenodias@users.noreply.github.com>

Revisores:
- @snifbr
- @marcio-machado76
- @vilelf
- @Rehzende
- @nerdtux
- @lipenodias
- @cflb

- [x] Garanta que seu **topic/feature/bugfix branch** tenha uma branch nomeada e não a sua branch main esteja no PR
- [x] Dê um titulo que expresse o objetivo do PR
- [ ] Associe seu PR a uma Issue criada no repositósito. Caso seja uma correção de linguagem ou pequenas correções, não é necessário
- [x] Descreva o objetivo do PR
- [x] Inclua links relevantes para a sua modificação/sugestão/correção
- [x] Descreva um passo-a-passo para testar o seu PR

## Issue

Sem issue associada.

## Objetivo

Criar um usuário local na VM com acesso SSH via chave pública.

## Referências

<https://cloud.google.com/compute/docs/instances/adding-removing-ssh-keys>
<https://registry.terraform.io/providers/hashicorp/google/latest/docs/resources/compute_instance#metadata>
<https://stackoverflow.com/questions/38645002/how-to-add-an-ssh-key-to-an-gcp-instance-using-terraform>

## Como testar

Baixar o repositório:

```sh
git clone --branch metadata-ssh https://github.com/snifbr/iac-modulo-compute-gcp/tree/metadata-ssh
```

Entrar no diretório:

```sh
cd template-modulo-terraform/how-to-use-this-module
```

Substituir a(s) chave(s) pública(s) no arquivo `terrafile.tf` por alguma chave pública válida no formato especificado no arquivo `README.md` na raiz do repositório, para que você possa testar o acesso ao final.

Executar os comandos:

```sh
## 1: Criar Service Account no GCP
make auth-create-sa

## 2: Criar policy
make auth-create-iam-policy

## 3: Adicionar policy
make auth-create-add-policy

## 4: Gerar arquivo com chave para autenticar no GCP
make auth-create-creds-file

## 5: Executar o terraform
make plan
make apply
```

Acessar a VM que foi instanciada no GCP e verificar a criação de conta de usuário local desejado e do arquivo no HOME_DIR `.ssh/authorized_keys` contendo a chave pública.

```sh
## 5: Executar o terraform
make destroy

```

2021-09-30 01:08 UTC, lipenodias commented
@gomex 

Precisamos que seja implementado o parametro access_config no modulo compute para que seja gerado um ip publico

```hcl

network_interface {
    network = "default"

    access_config {
      // Ephemeral public IP
    }
  }


```

2021-10-03 14:18 UTC, gomex requested changes

2021-10-03 14:18 UTC, gomex commented on how-to-use-this-module/Makefile
> +		--display-name="Terraform Service Account"
Precisamos colocar os valores abaixo no arquivo .env e não no .env.terraform, caso contrário, não funciona:

```
GCP_PROJECT=seu_project_id
GCP_TERRAFORM_SA=terraform
```

2021-10-03 15:08 UTC, lipenodias commented
Realizado o teste com o how-to-use-this-module com sucesso.

Alterações validadas

```hcl

make terraform-apply
STEP: terraform-apply - Execute terraform apply in terraform files
module.compute_gcp.google_compute_instance.default: Creating...
module.compute_gcp.google_compute_instance.default: Still creating... [10s elapsed]
module.compute_gcp.google_compute_instance.default: Still creating... [20s elapsed]
module.compute_gcp.google_compute_instance.default: Creation complete after 25s [id=projects/felipe-root-project/zones/us-central1-a/instances/teste]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

Outputs:

instance_private_ip = [
  tolist([
    "10.128.0.2",
  ]),
]
instance_public_ip = [
  tolist([
    "35.208.22.79",
  ]),
]

```

@gomex

2021-10-03 15:10 UTC, merged